from tkinter import *
from connect import db, c

def deposit(master,f1):
    f1.destroy()
    f2 = Frame(master)
    l1 = Label(f2, text="Enter Account Number",bg="lightblue",font=("Arial",10,"bold"))
    l1.grid(row=0,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e1 = Entry(f2,width=25)
    e1.grid(row=0,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    def check():
        c.execute("select * from bankapp;")
        data = c.fetchall()
        for var in data:
            if var[0]==int(e1.get()):
                ac = var[0]
                bal = var[7]
                l2 = Label(f2,text="Enter Amount to Deposit",bg="lightblue",font=("Arial",10,"bold"))
                l2.grid(row=1,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                e2 = Entry(f1,width=25)
                e2.grid(row=1,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                def depos():
                    amt = bal+int(e2.get())
                    cmd = f"update bankapp set balance={amt} where accno={ac};"
                    c.execute(cmd)
                    l3 = Label(f2,text="Amount Deposited Successfully",bg="lightblue",font=("Arial",10,"bold"))
                    l3.grid(row=2,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    b1 = Button(f2,text="Go Back",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=lambda: banking(master,f2))
                    b1.grid(row=3,column=1,ipadx=5,ipady=3,padx=3,pady=2)
                    db.commit()
                    db.close()
                b2 = Button(f2,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=depos)
                b2.grid(row=1,column=2,ipadx=5,ipady=3,padx=3,pady=2)
    b1 = Button(f2,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=check)
    b1.grid(row=0,column=2,ipadx=5,ipady=3,padx=3,pady=2)
    f2.config(bg="lightblue")
    f2.grid(row=0, column=0,padx=100,pady=100)


def withdrawal(master,f1):
    f1.destroy()
    f2 = Frame(master)
    l1 = Label(f2, text="Enter User ID ",bg="lightblue",font=("Arial",10,"bold"))
    l1.grid(row=0,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e1 = Entry(f2,width=25)
    e1.grid(row=0,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    l2 = Label(f2, text="Enter Password ",bg="lightblue",font=("Arial",10,"bold"))
    l2.grid(row=1,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e2 = Entry(f2,width=25,show="*")
    e2.grid(row=1,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    def check():
        c.execute("select * from bankapp;")
        data = c.fetchall()
        uid = e1.get()
        pas = e2.get()
        for var in data:
            if var[8]==uid and var[9]==pas:
                ac = var[0]
                bal = var[7]
                l2 = Label(f2,text="Enter Amount to Withdrawal",bg="lightblue",font=("Arial",10,"bold"))
                l2.grid(row=2,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                e3 = Entry(f2,width=25)
                e3.grid(row=2,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                def withdraw():
                    b2.destroy()
                    amt = bal-int(e3.get())
                    cmd = f"update bankapp set balance={amt} where accno={ac};"
                    c.execute(cmd)
                    l3 = Label(f2,text="Amount Withdrawal Successfully",bg="lightblue",font=("Arial",10,"bold"))
                    l3.grid(row=3,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    b1 = Button(f2,text="Go Back",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=lambda: banking(master,f2))
                    b1.grid(row=3,column=1,ipadx=5,ipady=3,padx=3,pady=2)
                    db.commit()
                b2 = Button(f2,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=withdraw)
                b2.grid(row=2,column=2,ipadx=5,ipady=3,padx=3,pady=2)
    b1 = Button(f2,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=check)
    b1.grid(row=2,column=1,ipadx=5,ipady=3,padx=3,pady=2)
    f2.config(bg="lightblue")
    f2.grid(row=0, column=0,padx=100,pady=100)


def check_balance(master,f1):
    f1.destroy()
    f2 = Frame(master)
    l1 = Label(f2, text="Enter User ID ",bg="lightblue",font=("Arial",10,"bold"))
    l1.grid(row=0,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e1 = Entry(f2,width=25)
    e1.grid(row=0,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    l2 = Label(f2, text="Enter Password ",bg="lightblue",font=("Arial",10,"bold"))
    l2.grid(row=1,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e2 = Entry(f2,width=25,show="*")
    e2.grid(row=1,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    def check():
        c.execute("select * from bankapp;")
        data = c.fetchall()
        uid = e1.get()
        pas = e2.get()
        for var in data:
            if var[8]==uid and var[9]==pas:
                ac = var[0]
                bal = var[7]
                l2 = Label(f2,text="Your Account Balance ",bg="lightblue",font=("Arial",10,"bold"))
                l2.grid(row=2,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                l3 = Label(f2, text=bal,bg="lightblue",font=("Arial",10,"bold"))
                l3.grid(row=2,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                b1 = Button(f2,text="Go Back",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=lambda: banking(master,f2))
                b1.grid(row=3,column=1,ipadx=5,ipady=3,padx=3,pady=2)
    b1 = Button(f2,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=check)
    b1.grid(row=2,column=1,ipadx=5,ipady=3,padx=3,pady=2)
    f2.config(bg="lightblue")
    f2.grid(row=0, column=0,padx=100,pady=100)
    
def new_account(master,f1):
    f1.destroy()
    f2 = Frame(master)
    l1 = Label(f1, text="First Name ",bg="lightblue",font=("Arial",10,"bold"))
    l2 = Label(f2, text="Last Name ",bg="lightblue",font=("Arial",10,"bold"))
    l3 = Label(f2, text="Date of Birth ",bg="lightblue",font=("Arial",10,"bold"))
    l4 = Label(f2, text="Mobile ",bg="lightblue",font=("Arial",10,"bold"))
    l5 = Label(f2, text="Aadhar ",bg="lightblue",font=("Arial",10,"bold"))
    l6 = Label(f2, text="Address ",bg="lightblue",font=("Arial",10,"bold"))
    l7 = Label(f2, text="Balance ",bg="lightblue",font=("Arial",10,"bold"))
    l8 = Label(f2, text="UserID ",bg="lightblue",font=("Arial",10,"bold"))
    l9 = Label(f2, text="Password ",bg="lightblue",font=("Arial",10,"bold"))
    l1.grid(row=0,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    l2.grid(row=1,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    l3.grid(row=2,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    l4.grid(row=3,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    l5.grid(row=4,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    l6.grid(row=5,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    l7.grid(row=6,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    l8.grid(row=7,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    l9.grid(row=8,column=0,ipadx=4,ipady=4,padx=4,pady=4)

    e1 = Entry(f2,width=25)
    e2 = Entry(f2,width=25)
    e3 = Entry(f2,width=25)
    e4 = Entry(f2,width=25)
    e5 = Entry(f2,width=25)
    e6 = Entry(f2,width=25)
    e7 = Entry(f2,width=25)
    e8 = Entry(f2,width=25)
    e9 = Entry(f2,width=25)
    e1.grid(row=0,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    e2.grid(row=1,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    e3.grid(row=2,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    e4.grid(row=3,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    e5.grid(row=4,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    e6.grid(row=5,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    e7.grid(row=6,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    e8.grid(row=7,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    e9.grid(row=8,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    def feed():
        fn = e1.get()
        ln = e2.get()
        dob = e3.get()
        mb = e4.get()
        aad = e5.get()
        ad = e6.get()
        bl = e7.get()
        ud = e8.get()
        pd = e9.get()
        cmd = "insert into bankapp(fname,lname,dob,mobile,aadhar,address,balance,userid,passwd) values('{}','{}','{}',{},{},'{}',{},'{}','{}');".format(fn,ln,dob,mb,aad,ad,bl,ud,pd)
        c.execute(cmd)
        l3 = Label(f2,text="Account Created Successfully",bg="lightblue",font=("Arial",10,"bold"))
        l3.grid(row=10,column=0,ipadx=4,ipady=4,padx=4,pady=4)
        cmd = "select accno from bankapp where userid={ud}"
        c.execute(cmd)
        accnt_no= c.fetchall()
        messagebox.showinfo("Details","Your Account Number is:"+str(accnt_no))
        b1 = Button(f2,text="Go Back",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=lambda: banking(master,f2))
        b1.grid(row=10,column=1,ipadx=5,ipady=3,padx=3,pady=2)
        db.commit()
        db.close()
    b1 = Button(f2,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=feed)
    b1.grid(row=9,column=1,ipadx=5,ipady=3,padx=3,pady=2)
    
    f2.config(bg="lightblue")
    f2.grid(row=0, column=0,padx=130,pady=40)

def edit_info(master,f1):
    f1.destroy()
    f2 = Frame(master)
    l1 = Label(f2, text="Enter User ID ",bg="lightblue",font=("Arial",10,"bold"))
    l1.grid(row=0,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e1 = Entry(f2,width=25)
    e1.grid(row=0,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    l2 = Label(f2, text="Enter Password ",bg="lightblue",font=("Arial",10,"bold"))
    l2.grid(row=1,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e2 = Entry(f2,width=25,show="*")
    e2.grid(row=1,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    def check():
        c.execute("select * from bankapp;")
        data = c.fetchall()
        uid = e1.get()
        pas = e2.get()
        def menu():
            f2 = Frame(master)
            b4 = Button(f2, text="User ID", width=15,height=2,bg="blue",fg="white",font=("times new roman",10,"bold"))
            b5 = Button(f2, text="Password", width=15,height=2,bg="blue",fg="white",font=("times new roman",10,"bold"))
            b6 = Button(f2, text="Mobile", width=15,height=2,bg="blue",fg="white",font=("times new roman",10,"bold"))
            b7 = Button(f2, text="Address", width=15, height=2,bg="blue",fg="white",font=("times new roman",10,"bold"))
            b8 = Button(f2, text="Aadhar", width=15, height=2,bg="blue",fg="white",font=("times new roman",10,"bold"))
            b9 = Button(f2, text="Go Back", width=15,height=2,bg="blue",fg="white",font=("times new roman",10,"bold"),command=lambda: banking(master,f2))
            b4.grid(row=0, column=0,padx=5,pady=4,ipadx=3,ipady=4)
            b5.grid(row=0, column=1,padx=5,pady=4,ipadx=3,ipady=4)
            b6.grid(row=1, column=0,padx=5,pady=4,ipadx=3,ipady=4)
            b7.grid(row=1, column=1,padx=5,pady=4,ipadx=3,ipady=4)
            b8.grid(row=2, column=0,padx=5,pady=4,ipadx=3,ipady=4)
            b9.grid(row=2, column=1,padx=5,pady=4,ipadx=3,ipady=4)
            f2.config(bg="lightblue")
            f2.grid(row=0, column=0,padx=100,pady=100)
        for var in data:
            if var[8]==uid and var[9]==pas:
                menu()
    b1 = Button(f2,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=check)
    b1.grid(row=2,column=1,ipadx=5,ipady=3,padx=3,pady=2)
    f2.config(bg="lightblue")
    f2.grid(row=0, column=0,padx=100,pady=100)
    
def login(master,f2):
    f2.destroy()
    f1 = Frame(master)
    l1 = Label(f1, text="Enter ID ",bg="lightblue",font=("Arial",10,"bold"))
    l1.grid(row=0,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e1 = Entry(f1,width=25)
    e1.grid(row=0,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    l2 = Label(f1, text="Enter Password ",bg="lightblue",font=("Arial",10,"bold"))
    l2.grid(row=1,column=0,ipadx=4,ipady=4,padx=4,pady=4)
    e2 = Entry(f1,width=25,show="*")
    e2.grid(row=1,column=1,ipadx=5,ipady=4,padx=3,pady=2)
    def check():
        c.execute("select * from bankapp;")
        data = c.fetchall()
        uid = e1.get()
        pas = e2.get()
        if e1.get()=='admin' and e2.get()=='admin@123':
            l3 = Label(f1, text="Search Account Number  ",bg="lightblue",font=("Arial",10,"bold"))
            l3.grid(row=2,column=0,ipadx=4,ipady=4,padx=4,pady=4)
            e3 = Entry(f1,width=25)
            e3.grid(row=2,column=1,ipadx=5,ipady=4,padx=3,pady=2)
            def acc_check():
                c.execute("select * from bankapp;")
                data = c.fetchall()
                def display(ls):
                    l3.forget
                    e3.forget
                    f1 = Frame(master)
                    lll = Label(f1,text="Account No ",bg="lightblue",font=("Arial",10,"bold"))
                    ll1 = Label(f1, text="First Name ",bg="lightblue",font=("Arial",10,"bold"))
                    ll2 = Label(f1, text="Last Name ",bg="lightblue",font=("Arial",10,"bold"))
                    ll3 = Label(f1, text="Date of Birth ",bg="lightblue",font=("Arial",10,"bold"))
                    ll4 = Label(f1, text="Mobile ",bg="lightblue",font=("Arial",10,"bold"))
                    ll5 = Label(f1, text="Aadhar ",bg="lightblue",font=("Arial",10,"bold"))
                    ll6 = Label(f1, text="Address ",bg="lightblue",font=("Arial",10,"bold"))
                    ll7 = Label(f1, text="Balance ",bg="lightblue",font=("Arial",10,"bold"))
                    ll8 = Label(f1, text="UserID ",bg="lightblue",font=("Arial",10,"bold"))
                    ll9 = Label(f1, text="Password ",bg="lightblue",font=("Arial",10,"bold"))
                    lll.grid(row=0,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll1.grid(row=1,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll2.grid(row=2,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll3.grid(row=3,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll4.grid(row=4,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll5.grid(row=5,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll6.grid(row=6,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll7.grid(row=7,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll8.grid(row=8,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    ll9.grid(row=9,column=0,ipadx=4,ipady=4,padx=4,pady=4)
                    
                    ac = StringVar()
                    fn = StringVar()
                    ln = StringVar()
                    dob = StringVar()
                    mb = StringVar()
                    aad = StringVar()
                    ad = StringVar()
                    bl = StringVar()
                    ud = StringVar()
                    pd = StringVar()
                    ell = Entry(f1,textvariable=ac,width=25)
                    el1 = Entry(f1,textvariable=fn,width=25)
                    el2 = Entry(f1,textvariable=ln,width=25)
                    el3 = Entry(f1,textvariable=dob,width=25)
                    el4 = Entry(f1,textvariable=mb,width=25)
                    el5 = Entry(f1,textvariable=aad,width=25)
                    el6 = Entry(f1,textvariable=ad,width=25)
                    el7 = Entry(f1,textvariable=bl,width=25)
                    el8 = Entry(f1,textvariable=ud,width=25)
                    el9 = Entry(f1,textvariable=pd,width=25)
                    ell.grid(row=0,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el1.grid(row=1,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el2.grid(row=2,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el3.grid(row=3,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el4.grid(row=4,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el5.grid(row=5,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el6.grid(row=6,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el7.grid(row=7,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el8.grid(row=8,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    el9.grid(row=9,column=1,ipadx=5,ipady=4,padx=3,pady=2)
                    ac.set(ls[0])
                    fn.set(ls[1])
                    ln.set(ls[2])
                    dob.set(ls[3])
                    mb.set(ls[4])
                    aad.set(ls[5])
                    ad.set(ls[6])
                    bl.set(ls[7])
                    ud.set(ls[8])
                    pd.set(ls[9])
                    b1 = Button(f1,text="Go Back",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=lambda: home(master,f1))
                    b1.grid(row=10,column=1,ipadx=5,ipady=3,padx=3,pady=2)
                    f1.config(bg="lightblue")
                    f1.grid(row=0, column=0,padx=130,pady=40)
                for var in data:
                    if var[0]==int(e3.get()):
                        lst = var
                        display(lst)
            b1 = Button(f2,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=acc_check)
            b1.grid(row=3,column=1,ipadx=5,ipady=3,padx=3,pady=2)
        for var in data:
            if var[8]==uid and var[9]==pas:
                banking(master,f1)
    b1 = Button(f1,text="Submit",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=check)
    b1.grid(row=2,column=0,ipadx=5,ipady=3,padx=3,pady=2)
    b2 = Button(f2,text="Go Back",width=10,height=1,bg="blue",fg="white",font=("times new roman",10,"bold"),command=lambda: banking(master,f2))
    b1.grid(row=2,column=1,ipadx=5,ipady=3,padx=3,pady=2)
    f1.config(bg="lightblue")
    f1.grid(row=0, column=0,padx=100,pady=100)


def home(master,f1):
    f1.destroy()
    f2 = Frame(master)
    b1 = Button(f2, text="New Account", width=15, height=2,bg="blue",fg="black",font=("times new roman",10,"bold"),command=lambda: new_account(master,f2))
    b2 = Button(f2, text="Login",width=15,height=2,bg="blue",fg="black",font=("times new roman",10,"bold"),command=lambda: login(master,f2))
    b3 = Button(f2, text="Exit",width=15,height=2,bg="blue",fg="black",font=("times new roman",10,"bold"),command=master.quit)
    b1.grid(row=2,column=2,padx=5,pady=4,ipadx=3,ipady=4)
    b2.grid(row=3,column=2,padx=5,pady=4,ipadx=3,ipady=4)
    b3.grid(row=4,column=2,padx=5,pady=4,ipadx=3,ipady=4)
    f1.config(bg="lightblue")
    f1.grid(row=9, column=5,padx=230,pady=100)


def banking(master,f2):
    f2.destroy()
    f1 = Frame(master)
    b5 = Button(f1, text="Deposit", width=15,height=2,bg="blue",fg="black",font=("times new roman",10,"bold"),command=lambda: deposit(master,f1))
    b6 = Button(f1, text="Withdrawal", width=15,height=2,bg="blue",fg="black",font=("times new roman",10,"bold"),command=lambda: withdrawal(master,f1))
    b7 = Button(f1, text="Check Balance", width=15,height=2,bg="blue",fg="black",font=("times new roman",10,"bold"),command=lambda: check_balance(master,f1))
    b8 = Button(f1, text="Edit Information", width=15, height=2,bg="blue",fg="black",font=("times new roman",10,"bold"),command=lambda: edit_info(master,f1))
    b9 = Button(f1, text="Go Back", width=15, height=2,bg="blue",fg="black",font=("times new roman",10,"bold"),command=lambda: home(master,f1))
    b5.grid(row=0, column=0,padx=5,pady=4,ipadx=3,ipady=4)
    b6.grid(row=0, column=1,padx=5,pady=4,ipadx=3,ipady=4)
    b7.grid(row=1, column=0,padx=5,pady=4,ipadx=3,ipady=4)
    b8.grid(row=1, column=1,padx=5,pady=4,ipadx=3,ipady=4)
    b9.grid(row=2, column=0,padx=5,pady=4,ipadx=3,ipady=4)
    f2.config(bg="lightblue")
    f2.grid(row=0,column=0,padx=180,pady=70)

root = Tk()
f1 = Frame(root)
f1.pack()
home(root,f1)
root.geometry("610x460")
root.title("Bank Management System")
root.config(bg="lightblue")
root.mainloop()
